[theme]
base="light"  # Options: "light" or "dark"
primaryColor="#2a9df4"
backgroundColor="#f9fcff"
secondaryBackgroundColor="#ffffff"
textColor="#333333"
font="sans serif"  # Options: "sans serif", "serif", "monospace"
